### PR TITLE
Extranonce antminer

### PR DESCRIPTION
**Pull request by hyperwang**
Modular implemention of extranonoce.subscribe which is disabled by default and can by enabled by URL optional parameter #xnsub.  
Fix  pool authorization bug.

### CODE REVIEW

**Comment by kenshirothefist** [comment]
@xjl2000, did you ever applied this commit?

**Comment by xjl2000** [comment]
yes,now all of bitmain miners support extranonce 2

**Comment by xjl2000** [comment]
i did it times ago,all of Bitmain miners support extranonoce.subscribe.i am sorry that i did not make a claim about it,but my fellow has taken over my job of cgminer.

**Comment by xjl2000** [comment]
just forgot to inform him about this

**Comment by kenshirothefist** [comment]
OK, but please just make sure that the patch in this pull request is actually applied (not the older, original patch, because the older original patch has the pool authorization bug).

**Comment by xjl2000** [comment]
the pull request which merged is the new one from hyperwang.testing on S4/S5/C1,worked well.

**Comment by kenshirothefist** [comment]
> the pull request which merged is the new one from hyperwang.testing on S4/S5/C1,worked well.

OK, great. Is the new cgminer already included in S4 and C1 firmware? (I know that it is in S5 firmware)

**Comment by xjl2000** [comment]
yes,they all included new cgminer supporting extranonce

**Comment by kenshirothefist** [comment]
We have received feedback from users, suggesting that the patch you're using is still the older one and not the one, discussed in this pull request. Once again, please include this newer patch since it fixes a small bug when switching to backup pools when using extranonce.subscribe. The correct patch is this:

https://github.com/nicehash/cgminer-ckolivas/commit/4e9c7ce68ed91ec9189d83c35b2237aca65f2b7f

Please use this patch in your future firmware releases. Thank you!

**Pull request closed without merging**
